"""plafond budgetaire de commande

Revision ID: 9cb79bb8f827
Revises: b015d1f1ac4f
Create Date: 2026-07-14 07:37:47.599605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb79bb8f827'
down_revision: Union[str, None] = 'b015d1f1ac4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parametres_officine', sa.Column('plafond_commande_fcfa', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parametres_officine', 'plafond_commande_fcfa')
    # ### end Alembic commands ###
