"""tables restantes references ventes parametres imports reset circuits

Revision ID: b015d1f1ac4f
Revises: 8ff44d6815a2
Create Date: 2026-07-09 14:06:19.440580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b015d1f1ac4f'
down_revision: Union[str, None] = '8ff44d6815a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_mappings',
    sa.Column('officine_id', sa.Uuid(), nullable=False),
    sa.Column('champ_cible', sa.String(), nullable=False),
    sa.Column('colonne_source', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['officine_id'], ['officines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_mappings_id'), 'column_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_column_mappings_officine_id'), 'column_mappings', ['officine_id'], unique=False)
    op.create_table('delais_circuit',
    sa.Column('officine_id', sa.Uuid(), nullable=False),
    sa.Column('circuit', sa.String(), nullable=False),
    sa.Column('dl_moy_jours', sa.Integer(), nullable=False),
    sa.Column('dl_max_jours', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['officine_id'], ['officines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('officine_id', 'circuit', name='uq_delai_circuit_officine')
    )
    op.create_index(op.f('ix_delais_circuit_id'), 'delais_circuit', ['id'], unique=False)
    op.create_index(op.f('ix_delais_circuit_officine_id'), 'delais_circuit', ['officine_id'], unique=False)
    op.create_table('import_logs',
    sa.Column('officine_id', sa.Uuid(), nullable=False),
    sa.Column('nom_fichier', sa.String(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('nb_lignes_total', sa.Integer(), nullable=True),
    sa.Column('nb_lignes_ok', sa.Integer(), nullable=True),
    sa.Column('nb_lignes_erreur', sa.Integer(), nullable=True),
    sa.Column('erreurs_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['officine_id'], ['officines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_logs_id'), 'import_logs', ['id'], unique=False)
    op.create_index(op.f('ix_import_logs_officine_id'), 'import_logs', ['officine_id'], unique=False)
    op.create_table('parametres_officine',
    sa.Column('officine_id', sa.Uuid(), nullable=False),
    sa.Column('dl_moy_jours', sa.Integer(), nullable=False),
    sa.Column('dl_max_jours', sa.Integer(), nullable=False),
    sa.Column('cycle_commande_jours', sa.Integer(), nullable=False),
    sa.Column('cout_commande', sa.Float(), nullable=False),
    sa.Column('taux_detention', sa.Float(), nullable=False),
    sa.Column('niveau_service_vital', sa.Float(), nullable=False),
    sa.Column('niveau_service_essentiel', sa.Float(), nullable=False),
    sa.Column('niveau_service_desirable', sa.Float(), nullable=False),
    sa.Column('niveau_service_non_renseigne', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['officine_id'], ['officines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parametres_officine_id'), 'parametres_officine', ['id'], unique=False)
    op.create_index(op.f('ix_parametres_officine_officine_id'), 'parametres_officine', ['officine_id'], unique=True)
    op.create_table('references',
    sa.Column('officine_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('forme', sa.String(), nullable=True),
    sa.Column('prix_cession', sa.Float(), nullable=True),
    sa.Column('prix_public', sa.Float(), nullable=True),
    sa.Column('stock_actuel', sa.Float(), nullable=False),
    sa.Column('circuit', sa.String(), nullable=True),
    sa.Column('ved', sa.String(), nullable=True),
    sa.Column('risque_fournisseur_jours', sa.Integer(), nullable=False),
    sa.Column('classe', sa.String(), nullable=True),
    sa.Column('fsn', sa.String(), nullable=True),
    sa.Column('cmm', sa.Float(), nullable=True),
    sa.Column('cmmax', sa.Float(), nullable=True),
    sa.Column('sigma', sa.Float(), nullable=True),
    sa.Column('z_service', sa.Float(), nullable=True),
    sa.Column('ss', sa.Float(), nullable=True),
    sa.Column('pc', sa.Float(), nullable=True),
    sa.Column('eoq', sa.Float(), nullable=True),
    sa.Column('ss_periodique', sa.Float(), nullable=True),
    sa.Column('niveau_recompletement', sa.Float(), nullable=True),
    sa.Column('qte_a_commander', sa.Float(), nullable=True),
    sa.Column('qte_commander_continu', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('couverture_jours', sa.Float(), nullable=True),
    sa.Column('tresorerie_liberee', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['officine_id'], ['officines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_code'), 'references', ['code'], unique=False)
    op.create_index(op.f('ix_references_id'), 'references', ['id'], unique=False)
    op.create_index(op.f('ix_references_officine_id'), 'references', ['officine_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('ventes_mensuelles',
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('mois_index', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventes_mensuelles_id'), 'ventes_mensuelles', ['id'], unique=False)
    op.create_index(op.f('ix_ventes_mensuelles_reference_id'), 'ventes_mensuelles', ['reference_id'], unique=False)
    # NB : autogenerate signale aussi un "changement de type" NUMERIC -> Uuid
    # sur officines.id / users.id / users.officine_id. C'est un faux positif
    # connu (SQLite n'a pas de type UUID natif, la comparaison d'affinité de
    # type est trompeuse) — ces colonnes n'ont pas réellement changé depuis la
    # migration précédente, ces alter_column ont donc été retirés volontairement.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventes_mensuelles_reference_id'), table_name='ventes_mensuelles')
    op.drop_index(op.f('ix_ventes_mensuelles_id'), table_name='ventes_mensuelles')
    op.drop_table('ventes_mensuelles')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_references_officine_id'), table_name='references')
    op.drop_index(op.f('ix_references_id'), table_name='references')
    op.drop_index(op.f('ix_references_code'), table_name='references')
    op.drop_table('references')
    op.drop_index(op.f('ix_parametres_officine_officine_id'), table_name='parametres_officine')
    op.drop_index(op.f('ix_parametres_officine_id'), table_name='parametres_officine')
    op.drop_table('parametres_officine')
    op.drop_index(op.f('ix_import_logs_officine_id'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_id'), table_name='import_logs')
    op.drop_table('import_logs')
    op.drop_index(op.f('ix_delais_circuit_officine_id'), table_name='delais_circuit')
    op.drop_index(op.f('ix_delais_circuit_id'), table_name='delais_circuit')
    op.drop_table('delais_circuit')
    op.drop_index(op.f('ix_column_mappings_officine_id'), table_name='column_mappings')
    op.drop_index(op.f('ix_column_mappings_id'), table_name='column_mappings')
    op.drop_table('column_mappings')
    # ### end Alembic commands ###
