"""sorties detaillees pour import commande

Revision ID: dfb0d2952f72
Revises: 9cb79bb8f827
Create Date: 2026-07-14 09:34:27.254794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb0d2952f72'
down_revision: Union[str, None] = '9cb79bb8f827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_logs', sa.Column('sorties_totales', sa.Float(), nullable=True))
    op.add_column('references', sa.Column('sorties_derniere_commande', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('references', 'sorties_derniere_commande')
    op.drop_column('import_logs', 'sorties_totales')
    # ### end Alembic commands ###
